CXXFLAGS +=-I../vendor -I../vendor/inja -I../vendor/rapidyaml
CXXFLAGS +=-g -O0
LIBS = -lpthread -lgtest -lgtest_main

SRC := $(wildcard **.cc)
SRC_TEST := $(filter-out ecb.cc, $(SRC))

OBJS=$(SRC_TEST:.cc=.o)

test_ecb: $(OBJS)
	$(CXX) $(CXXFLAGS) $(LIBS) $(BUILD_INFO) $(OBJS) -o test_ecb
