export VERSION = 1.6.0

export CXXFLAGS += -DMAKEFILE_BUILD_VERSION=\""1.6.0\""
export CXXFLAGS += -DMAKEFILE_BUILD_NUMBER=\""$(shell git rev-list --count main)\""
export CXXFLAGS += -DMAKEFILE_BUILD_DIRTY=\""$(shell [ -n "$$(git status --porcelain)" ] && echo "-dirty")\""
export CXXFLAGS += -DMAKEFILE_BUILD_HASH=\""$(shell git rev-parse HEAD)\""
export CXXFLAGS += -DMAKEFILE_BUILD_DATE=\""$(shell date -Iseconds)\""
