CXXFLAGS +=-I../vendor -I../vendor/inja -I../vendor/rapidyaml
CXXFLAGS +=-g -O0
LDLIBS += -lstdc++fs

SRC := $(wildcard **.cc)
SRC_EXE:=$(filter-out $(wildcard *_test.cc) ecb_epics.cc, $(SRC))

OBJS=$(SRC_EXE:.cc=.o)
OBJS_TEST=$(SRC:.cc=.o)

ecb: $(OBJS)

test_ecb: $(OBJS_TEST)

clean:
	rm -rf *.o
	rm -rf ecb
