CXXFLAGS +=-I../vendor -I../vendor/inja -I../vendor/rapidyaml
CXXFLAGS +=-g -O0
LDLIBS += -lpthread -lgtest -lgtest_main -lstdc++fs

SRC := $(wildcard **.cc)
SRC_TEST := $(filter-out ecb.cc ecb_epics.cc, $(SRC))

OBJS=$(SRC_TEST:.cc=.o)

test_ecb: $(OBJS)
	$(CXX) $(CXXFLAGS) $(LIBS) $(BUILD_INFO) $(OBJS) $(LDLIBS) -o test_ecb
